name: GH Pages

on:
  push:
    branches:
      - master

jobs:
  ghpages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable web configuration
        run: flutter config --enable-web
      - name: Install dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web --release --base-href '/${{ github.event.repository.name }}/' --dart-define=URL=${{ secrets.URL }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: web/build/web
